# Generated by Django 4.2 on 2023-09-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_center', '0002_studycenter_director_studycenter_district_and_more'),
        ('account', '0002_user_is_phone_verified_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary_percentage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('director', 'Director'), ('adminstrator', 'Adminstrator'), ('student', 'Student')], default='teacher', max_length=13, verbose_name='User type'),
        ),
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_percentage', models.FloatField(blank=True, null=True, verbose_name='Salary percentage')),
                ('subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to='study_center.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to='study_center.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
