# Generated by Django 4.2 on 2023-09-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_salary_percentage_remove_user_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacheruser',
            old_name='subjects',
            new_name='subject',
        ),
    ]
