# Generated by Django 4.2 on 2023-09-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_subjects_teacheruser_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='subjects',
            new_name='subject',
        ),
    ]
