# Generated by Django 4.2 on 2023-09-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_district_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': '5.District'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': '4.Regions'},
        ),
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name': 'StudentUser', 'verbose_name_plural': '3.StudentUsers'},
        ),
        migrations.AlterModelOptions(
            name='teacheruser',
            options={'verbose_name': 'TeacherUser', 'verbose_name_plural': '2.TeacherUsers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': '1.Users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password_or_id_number',
            new_name='passport_or_id_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('director', 'Director'), ('adminstrator', 'Adminstrator'), ('student', 'Student')], default='director', max_length=13, verbose_name='User type'),
        ),
    ]
