# Generated by Django 4.2 on 2023-10-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_center', '0009_studyday_study_center_time_study_center'),
        ('account', '0007_alter_district_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Salary percentage'),
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='study_center.subject'),
        ),
    ]
