# Generated by Django 4.2 on 2023-09-13 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_center', '0004_delete_message_alter_day_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Contact Type',
                'verbose_name_plural': '2.Contact Types',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message text')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('reveiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveiver_user', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='study_center.studycenter', verbose_name='Study Center')),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': '1.Letters',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='study_center.studycenter', verbose_name='Study Center')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='letter.contacttype', verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': '3.Contacts',
            },
        ),
    ]
