# Generated by Django 4.2 on 2023-09-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_district_options_alter_region_options_and_more'),
        ('study_center', '0006_alter_subjectgroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'PaymetType',
                'verbose_name_plural': 'PaymetTypes',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Month')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('money', 'Money')], default='percentage', max_length=10, verbose_name='Type')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='study_center.studycenter', verbose_name='Study Center')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('is_billing', models.BooleanField(default=True, verbose_name='Is Billing')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('payment_date', models.DateField(auto_now=True, verbose_name='Payment Date')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='payment.discount', verbose_name='Discount')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='payment.season', verbose_name='Month')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='payment.paymettype', verbose_name='Payment Type')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='account.studentuser', verbose_name='Student')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='study_center.studycenter', verbose_name='Study Center')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='study_center.subjectgroup', verbose_name='Study Group')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
            },
        ),
    ]
