# Generated by Django 4.2 on 2023-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='end_date',
            field=models.DateField(auto_now=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='discount',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='start_date'),
        ),
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
