# Generated by Django 4.2 on 2023-09-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_discount_end_date_discount_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'Billing', 'verbose_name_plural': '1.Billings'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': '2.Discounts'},
        ),
        migrations.AlterModelOptions(
            name='paymettype',
            options={'verbose_name': 'PaymetType', 'verbose_name_plural': '3.PaymetTypes'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Season', 'verbose_name_plural': '4.Seasons'},
        ),
    ]
