# Generated by Django 4.2 on 2023-10-24 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_alter_billing_options_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
