# Generated by Django 4.2 on 2023-09-12 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycenter',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_centers', to=settings.AUTH_USER_MODEL, verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='studycenter',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_centers', to='account.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='studycenter',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_centers', to='account.region', verbose_name='Region'),
        ),
    ]
