# Generated by Django 4.2 on 2023-09-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_salary_percentage_remove_user_subjects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_center', '0002_studycenter_director_studycenter_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Day',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Room number')),
                ('room_size', models.ImageField(upload_to='', verbose_name='Room size')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='study_center.studycenter', verbose_name='Study Center')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s', to='study_center.day', verbose_name='Day')),
            ],
            options={
                'verbose_name': 'StudyDay',
                'verbose_name_plural': 'StudyDays',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update profile')),
                ('start_at', models.DateField(auto_now=True, verbose_name='Start at')),
                ('status', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_groups', to='study_center.room')),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='subject_groups', to='account.studentuser')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='study_center.studycenter', verbose_name='Study Center')),
                ('study_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_groups', to='study_center.studyday')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='study_center.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'StudyGroup',
                'verbose_name_plural': 'StudyGroups',
            },
        ),
        migrations.AddField(
            model_name='studyday',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_center.time', verbose_name='Time'),
        ),
    ]
