# Generated by Django 4.2 on 2023-09-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_center', '0005_alter_subjectgroup_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectgroup',
            options={'verbose_name': 'Study Group', 'verbose_name_plural': '2.Study Groups'},
        ),
    ]
