# Generated by Django 4.2 on 2023-09-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_center', '0006_alter_subjectgroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.IntegerField(verbose_name='Room size'),
        ),
    ]
