# Generated by Django 4.2 on 2023-09-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_district_options_alter_region_options_and_more'),
        ('study_center', '0007_alter_room_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='account.teacheruser', verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='account.teacheruser', verbose_name='Teacher'),
        ),
    ]
