# Generated by Django 4.2 on 2023-10-24 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_center', '0009_studyday_study_center_time_study_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='students',
            field=models.ManyToManyField(related_name='subject_groups_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
